### ISSUE TITLE
默认使用80端口不妥

### ISSUE THREAD

**Issue by vimac** [MashiMaroLjc/ML-and-DM-in-action#1]
*nix (Linux, BSD, OS X) 环境下面，小于1024的端口是需要root权限才可以打开的，所以也就是需要sudo才可以运行这个程序，所以不是很妥当
而且，很多开发者都会在本地开着nginx, apache之类的服务器，一般也占着80，所以默认80会造成一些不必要的麻烦

当然了，这个并不是个大问题，可以考虑改个小众端口（也可以设计成从命令行参数读取），供你参考

**Comment by MashiMaroLjc** [comment]
已经update了，现在可以在命令行读取了
