### ISSUE TITLE
json

### ISSUE THREAD

**Issue by CsterKuroi** [MashiMaroLjc/ML-and-DM-in-action#4]
`{"neighbor2": {"0": {"neighbor3": {"0": "[-1, -1]", "-1": "[-1, -1]", "1": {"neighbor1": {"0": "[2, 2]", "-1": "[-1, -1]", "1": "[2, 5]"}}}}, "-1": "[-1, -1]", "1": {"neighbor1": {"0": {"neighbor3": {"0": "[3, 1]", "-1": "[-1, -1]", "1": "[1, 5]"}}, "-1": "[-1, -1]", "1": {"neighbor3": {"0": "[3, 5]", "-1": "[-1, -1]"}}}}}}`
[2, 5] 的意义是指neighbor2 权重5么？

**Comment by MashiMaroLjc** [comment]
不是的。

你可能理解有误，这段JSON**不是表示决策树的信息，而是表示决策树的结构**

在决策树的训练时是这样的，假设一个向量`[1,1,0,0]`,那么这个向量表示在该子下有两颗子连接在一起，`1`表示敌方的棋子，`0`表示空位，`-1`表示不可放子，那么，机器应该下在`2`号位，（列表所以从0开始）,但在测试时发现，**机器会永远以最右下方的情况为准(因为我是循环扫描)，而不是以棋局的紧急为准（比如对方在一处连了两子，在别处连了三子，这显然应该优先阻止三子的地方）**，所以加了一个权重，以表示紧急程度**5最高，-1最低**。

**Comment by CsterKuroi** [comment]
那我应该理解对了。
